### ISSUE TITLE
Characters displayed incorrectly in some browsers

### ISSUE THREAD

**Issue by sheepa** [tsl0922/ttyd#848]
**Describe the bug**
Characters are displayed incorrectly in some browsers (Win10/Brave & OSX/Chrome), please see screenshot: https://i.imgur.com/y0SqLy7.png

Rollbacking to v.1.6.1 (079aa68) fixes the issue.

**Comment by andjo** [comment]
I think it's related to this: https://github.com/xtermjs/xterm.js/issues/2686
Turning off fingerprinting protection fixes this in Brave for me. It's not a viable workaround though since it can't be done per site.

**Comment by ntlug** [comment]
@andjo that's a different issue.  Fonts in Firefox (for example) do not render well, as the screenshot presented here shows.  Seems to work on in Chrome.  Some people workaround the problem with wider spaced fonts, but they aren't very pretty.  Some have had issues with vertical overlap as well (but I haven't seen this yet).

**Comment by sheepa** [comment]
This seems to have been fixed in 1.7 (Tested Win10/Brave). Thanks!

**Comment by tsl0922** [comment]
try `ttyd -t rendererType=dom`

**Comment by ntlug** [comment]
I still have this issue as well in Firefox, even with 1.7 and -t rendererType=dom did not help.
